### ISSUE TITLE
Preprint link not working

### ISSUE THREAD

**Issue by Marius1311** [StatBiomed/UniTVelo#1]
Hi all, this looks interesting but the link to your preprint is broken - can you please point us to it? Thanks! 

Ping @michalk8

**Comment by michaelgmz** [comment]
Hi Marius, thx for your interest in this project. Sorry we haven't provided the preprint link as we aim to upload it to bioRxiv in a few weeks once going through the initial submission process. I'll email you the pdf file though.

**Comment by Marius1311** [comment]
Thanks, I understand! Thanks for offering to send the pdf, that would be great. Thanks!
