### ISSUE TITLE
Why does UniTVelo v0.2.4.2 depend on a specified pandas version (pandas==1.4.2)

### ISSUE THREAD

**Issue by altairwei** [StatBiomed/UniTVelo#19]
Hi,

Thank you for this fantastic tool! I found a dependency problem when attempted to upgrade UniTVelo from 0.2.3 to 0.2.4.  My project depends on the `scprep` package which requires a certain version (<1.4,>=0.25) of `pandas`. However, in the commit https://github.com/StatBiomed/UniTVelo/commit/927bc2ae059c0ddd48f1f8e0c1c60c775af59fd4 , a specified pandas version (v1.4.2) was added to `setup.py` , which conflicts with `scprep`.

Is this a bug? Will I miss critical features if I stay on version 0.2.3?

Best,
Altair

**Comment by michaelgmz** [comment]
Hi Altair,

Thx for your interest in this project. 
I guess it's safe for you to stay on version 0.2.3 for now as the major difference with 0.2.4 is I'm trying to add an alternative feature for the model initialization part, which doesn't affect the core module of UniTVelo, and still the performance of this alternative initialization needs to be examined.

So you generally won't miss any results, and yes thx for spotting this out, I'll fix it shortly.

Bests
