### ISSUE TITLE
'KeyError: 'The optimizer cannot recognize variable log_gamma:0. 

### ISSUE THREAD

**Issue by Mnew1288** [StatBiomed/UniTVelo#20]
Hi,

Thank you a lot for developing this great tool! I got the following error when I run the Mouse Erythroid dataset under UniTVelo mode. No problem under scVelo stochastic or scVelo dynamic mode.

'KeyError: 'The optimizer cannot recognize variable log_gamma:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.''

Best

**Comment by michaelgmz** [comment]
Hi there,

Thx for spotting this out and it seems this error is related to a newer version of Tensorflow. 

Quote from official website, 
"This is the default Keras optimizer base class until v2.10 (included). In v2.11 and later, [tf.keras.optimizers.Optimizer](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer) points to a new base class implementation. The legacy class won't be deleted in the future and will continue to be available at [tf.keras.optimizers.legacy.Optimizer](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/legacy/Optimizer)."

I've fixed this issue and feel free to update UniTVelo to v0.2.5. 

Bests

**Comment by Mnew1288** [comment]
Thanks for the quick update!!

It seems to be working now.

Best
