### ISSUE TITLE
Error in low UMI count dataset

### ISSUE THREAD

**Issue by AlexanderAivazidis** [StatBiomed/UniTVelo#23]
Hi!

I tried to run UniTVelo on the MouseBoneMarrow dataset with very low UMI counts that you gave to me at some point. I found that that while the "unified" model works the "independent model" gives the below error. Do you know what to do about this?
![image](https://user-images.githubusercontent.com/46488185/209324774-24359373-def4-4638-9167-499bf237911f.png)

Thanks a lot!
Best wishes,

Alexander

**Comment by michaelgmz** [comment]
Hi Alexander,

Thx for raising this issue, this error has been fixed. Kindly please upgrade the package and try again.

Bests,
Mingze
