### ISSUE TITLE
preprocessing script for input to `SuppFig6_Oligodendrocyte.ipynb`

### ISSUE THREAD

**Issue by cameronraysmith** [StatBiomed/UniTVelo#26]
Would you be able to provide the pre-processing script used to produce

```python
11 "dataset = '../data/Oligo/oligo_lite.h5ad'
```

presumably from [OligoPons_metafromSten.loom](http://pklab.med.harvard.edu/ruslan/velocity/oligos/OligoPons_metafromSten.loom) or [oligos_info.rds](http://pklab.med.harvard.edu/ruslan/velocity/oligos/oligos_info.rds) that is
referenced at https://github.com/StatBiomed/UniTVelo/blame/8370e50e6cec261b6791f0e714736cb54f3c4088/notebooks/SuppFig6_Oligodendrocyte.ipynb#L11 ?

Many thanks!

**Comment by cameronraysmith** [comment]
If you would be able to just provide us a copy of the `oligo_lite.h5ad` file that would also be helpful. Many thanks!

**Comment by michaelgmz** [comment]
Hi Cameron,

So sorry for this late reply as I was on leave recently and didn't check email frequently. 
For the orighinal .h5ad file, I uploaded datasets we used [here](https://connecthkuhk-my.sharepoint.com/personal/gmz1229_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fgmz1229%5Fconnect%5Fhku%5Fhk%2FDocuments%2FUniTVelo%20Datasets&ga=1), hope this is what you were looking for.

As for the pre-processing script, I have some trouble accessing the server right now, I'll take a look next Monday and get back to you then. So sorry for ths inconvenience.

But firstly hope the .h5ad file in the above link helps.

Mingze

**Comment by cameronraysmith** [comment]
Hi @michaelgmz ,

Thank you for your response. I suspect this is what we need, but the link you provided requires authentication:

~~`https://connecthkuhk-my.sharepoint.com/personal/gmz1229_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fgmz1229%5Fconnect%5Fhku%5Fhk%2FDocuments%2FUniTVelo%20Datasets&ga=1`~~

Please post an accessible link at your convenience.

We will very much appreciate a copy of the pre-processing script as well, but we understand if you are having a server access issue that this may result in a delay.

Many thanks,
Cameron

**Comment by michaelgmz** [comment]
Hi @cameronraysmith ,

Please have a look if this link works? 
https://connecthkuhk-my.sharepoint.com/:f:/g/personal/gmz1229_connect_hku_hk/EkC47RWWUrtOqcWzJ0neDGEBKLZTHWZW7PPe3vhUo9sn6g?e=jOm152

Bests,
Mingze

**Comment by cameronraysmith** [comment]
That works! Thank you so much for your help Mingze! 
When we receive the link to the preprocessing script this issue can likely be closed.

**Comment by michaelgmz** [comment]
Hi @cameronraysmith ,

Check if the link for the pre-processing script works, the generated .h5ad file might have a few differences in adata.obs compared with oligo_lite.h5ad, but others should be the same, count matrices, labels, etc.

https://connecthkuhk-my.sharepoint.com/:f:/g/personal/gmz1229_connect_hku_hk/ElTH4WMWavdMipQUf6cHPx0BGsS0NoP8b4lqq4fmyKTQMQ?e=h4y0hE

Mingze

**Comment by cameronraysmith** [comment]
Hi @michaelgmz ,

Thank you very much! I will close the issue.

Best,
Cameron
